engines:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  rubocop:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
ratings:
  paths:
  - "app/**/*"
  - "**.rb"
exclude_paths:
- app/assets/**/*
- app/config/locales/**/*
- app/views/**/*
- bin/**/*
- config/**/*
- db/**/*
- doc/**/*
- lib/**/*
- public/**/*
- spec/**/*
- vendor/**/*
- .codeclimate.yml
- .env-*
- .gitignore
- .rspec
- .slugignore
- .travis.yml
- Gemfile
- Gemfile.lock
- Procfile
- README.md
- Rakefile
- config.ru
- docker-compose.yml
